{
  parserClass="com.github.guillaumetaffin.intellij.matlab.language.parser.MatlabParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Matlab"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.guillaumetaffin.intellij.matlab.language.parser.psi"
  psiImplPackage="com.github.guillaumetaffin.intellij.matlab.language.parser.psi.impl"

  elementTypeHolderClass="com.github.guillaumetaffin.intellij.matlab.language.parser.psi.MatlabTypes"
  elementTypeClass="com.github.guillaumetaffin.intellij.matlab.language.parser.psi.MatlabElementType"
  tokenTypeClass="com.github.guillaumetaffin.intellij.matlab.language.lexer.tokens.MatlabTokenType"

  parserImports=[
    "static com.github.guillaumetaffin.intellij.matlab.language.lexer.tokens.Tokens.*"
  ]

  generateTokens=false

//  extends(".*type_ref")=type_ref
  extends(".*value_expr")=value_expr

  tokens=[
    EQUAL="="
    SEMICOLON=";"
    PLUS="+"
    MINUS="-"
    MUL="*"
    DIV="/"
    POW="^"
    ELEMENT_WISE_MUL=".*"
    ELEMENT_WISE_DIV="./"
    ELEMENT_WISE_POW=".^"
    OPEN_PARENS="("
    CLOSE_PARENS=")"
    OPEN_BRACKET="["
    CLOSE_BRACKET="]"
    COMMA=","
    SINGLE_QUOTE="'"
    ID="regexp:[a-zA-Z][a-zA-Z_0-9]*"
    INT_LITERAL="regexp:[0-9][0-9_]*"
//    STRING_LITERAL='regexp:\"([^\"\r\n]|(\\\"))*\"'
//    LINE_COMMENT="regexp://.*"
//    BLOCK_COMMENT="regexp:/\*[\s\S]*?\*/"
    LINE_BREAK="regexp:[\n\r]+"
    WHITESPACE="regexp:[ \t\f]+"
  ]
}

matlabFile ::= top_level_item? (statement_separator top_level_item?)*

statement_separator ::= ";" | LINE_BREAK

top_level_item ::= binding_statement
    | value_expr

binding_statement ::= ID "=" value_expr

value_expr ::= unary_value_expr_group
    | composed_value_expr_group
    | primary_value_expr_group


private unary_value_expr_group ::= transpose_value_expr
    | unary_math_value_expr

private composed_value_expr_group ::= math_value_expr

private primary_value_expr_group ::= func_call_value_expr
    | literal_value_expr

transpose_value_expr ::= value_expr "'"

unary_math_value_expr ::= "-" value_expr

math_value_expr ::= value_expr math_operator value_expr

func_call_value_expr ::= ref_id "(" func_call_parameters  ")"
func_call_parameters ::= value_expr ("," value_expr)*

literal_value_expr ::= ref_id
    | array_literal
    | INT_LITERAL

array_literal ::= "[" ( value_expr ("," | ";")? )* "]"

ref_id ::= ID

math_operator ::= "+" | "-" | "*" | "/" | "^" | ".*" | "./" | ".^"